# Deploy to AWS using the planned output from the build.yaml file

name: 'Terraform Deploy'

on:
  # TODO: undo after testing is complete
  push:
    branches: ["Automation"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
     run:
      shell: bash
      working-directory: ./deployment/aws/terraform

    steps:
      - name: Checkout Github repository
        uses: actions/checkout@v4 
      
      - name: DEBUG - print default working dir and file contents
        run: pwd && ls
      
      - name: DEBUG - print workflow dir and file contents
        working-directory: ./.github/workflows/
        run: pwd && ls

      - name: DEBUG - print actions dir and file contents
        working-directory: ./.github/actions/setup-action/
        run: pwd && ls

      - name: Initialize runner
        uses: ./.github/actions/setup-action

      - name: Download Plan File
        uses: actions/download-artifact@v4
        with: 
          name: "${GITHUB_SHA}"

      - name: Terraform Init
        uses: terraform init
      
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Deploy
        run: terraform apply "${GITHUB_SHA}" 



