# Use Terraform to init, validate, plan w/ output file and deploy (if changes merged to 'main'). Archive output file used for GHA Artifact for deployment.

name: 'Terraform Build and Deploy'

on:
  workflow_call: 
    inputs: 
      artifact-name: 
        required: true
        type: string
        description: Name of the file to be deployed to S3

# Redundant, however leaving here for good measure as this is required
permissions:
  id-token: write
  contents: read  

jobs:
  automate:
    name: 'Terraform Build, Validation and Deployment'
    runs-on: ubuntu-latest
    # automation only runs if previous workflow was successful

    env: 
      TF_VAR_AWS_ROOT_USER: ${{ secrets.AWS_ROOT_USER }}
      TF_VAR_AWS_IAM_USER: ${{ secrets.AWS_IAM_USER}}
      TF_VAR_AWS_DEPLOYMENT_ROLE: ${{ secrets.AWS_DEPLOYMENT_ROLE}}

    defaults:
      run:
        shell: bash
        working-directory: ./deployment/aws/terraform

    steps:
      - name: Checkout Github repository
        uses: actions/checkout@v4 

      - name: Initialize runner
        uses: ./.github/actions/setup-action

      - name: Download cached HTML artifact from Github Artifact cache
        uses: actions/download-artifact@v4
        with: 
          name: GoogleDriveFile
          path: ./deployment/aws/terraform
      
      # TODO: download terraform state files - cached for up to 90 days

      - name: Check if Google Drive file downloaded properly
        run: |
          if [ -s index.html ]; then
            echo "Google Drive file downloaded and is not empty."
          else 
            echo "Either Google Drive file was not downloaded OR is empty."
          

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform Format
      #   run: terraform fmt -check
      
      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   run: terraform plan -input=false -out=$GITHUB_SHA

      # - name: Archive plan file 
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ github.sha }}
      #     path: ./
    
      # # Deployment should only run once changes have been merged into master
      # - name: Terraform Deploy
      #   if: github.event_name == 'push'
      #   run: terraform apply $GITHUB_SHA
