# Use Terraform to init, validate, plan w/ output file and deploy (if changes merged to 'main'). Archive output file used for GHA Artifact for deployment.

name: 'Terraform Build and Deploy'

on:
  workflow_run: 
    workflows: ['Download Google Drive File']
    types: [completed]

# Redundant, however leaving here for good measure as this is required
permissions:
  id-token: write
  contents: read  

jobs:
  automate:
    name: 'Terraform Build, Validation and Deployment'
    runs-on: ubuntu-latest
    # automation only runs if previous workflow was successful

    env: 
      TF_VAR_AWS_ROOT_USER: ${{ secrets.AWS_ROOT_USER }}
      TF_VAR_AWS_IAM_USER: ${{ secrets.AWS_IAM_USER}}
      TF_VAR_AWS_DEPLOYMENT_ROLE: ${{ secrets.AWS_DEPLOYMENT_ROLE}}
      TF_ARTIFACTS_NAME: TFStateAndLockFiles

    defaults:
      run:
        shell: bash
        working-directory: ./deployment/aws/terraform

    steps:
      - name: Checkout Github repository
        uses: actions/checkout@v4 

      - name: Initialize runner
        uses: ./.github/actions/setup-action

      - name: Download cached HTML artifact from Github Artifact cache
        uses: actions/download-artifact@v4
        with: 
          name: GoogleDriveFile
          path: ./deployment/aws/terraform
      
      - id: DriveFileVerification
        name: Check if Google Drive file downloaded properly from cache
        run: |
          if [ -s index.html ]; then
            echo "nonEmpty=true" >> $GITHUB_OUTPUT
            echo "Google Drive file downloaded and is not empty."
          else 
            echo "nonEmpty=false" >> $GITHUB_OUTPUT
            echo "Either Google Drive file was not downloaded OR is empty."
          fi

      - name: Download Terraform State and Lock Files
        uses: actions/download-artifact@v4
        with: 
          name: ${{env.TF_ARTIFACTS_NAME}}
          path: ./deployments/aws/terraform
        continue-on-error: true
          
      - name: Verify Terraform TfState File Downloaded
        run: |
          if [ -s terraform.tfstate ]; then
            echo "Terraform tfstate file downloaded and is not empty."
          else 
            echo "Terraform tfstate file was not downloaded OR is empty."
          fi

      - name: Verify Terraform Lock-HCL File Downloaded
        run: |
          if [ -s .terraform.lock.hcl ]; then
            echo "Terraform Lock-HCL file downloaded and is not empty."
          else 
            echo "Terraform Lock-HCL file was not downloaded OR is empty."
          fi

      - name: Terraform Init
        run: terraform init
        if: ${{steps.DriveFileVerification.outputs.nonEmpty}}

      - name: Terraform Format
        run: terraform fmt -check
        if: ${{steps.DriveFileVerification.outputs.nonEmpty}}
      
      - name: Terraform Validate
        run: terraform validate
        if: ${{steps.DriveFileVerification.outputs.nonEmpty}}

      - name: Terraform Plan
        run: terraform plan -input=false -out=$GITHUB_SHA
        if: ${{steps.DriveFileVerification.outputs.nonEmpty}}

      - name: Archive plan file 
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: ./${{ github.sha }}
        if: ${{steps.DriveFileVerification.outputs.nonEmpty}}
    
      # Deployment should only run once changes have been merged into master
      # - name: Terraform Deploy
      #   if: github.event_name == 'push' && ${{steps.DriveFileVerification.outputs.nonEmpty}}
      #   run: terraform apply $GITHUB_SHA

      # Archive the Terraform state and lock-hcl files
      - name: Store TfState and Lock-HCL Files
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with: 
          name: ${{env.TF_ARTIFACTS_NAME}}
          path: | 
            terraform.tfstate
            .terraform.lock.hcl
          include-hidden-files: true
          overwrite: true

      # Cleanup - ensure downloaded artifacts are removed from runner
      - name: Cleanup - remove artifacts
        if: always()
        run: |
          rm -f terraform.tfstate
          rm -f .terraform.lock.hcl
          rm -f index.html
        