# Deploy to AWS using the planned output from the build.yaml file

name: 'Terraform Deploy'

on:
  workflow_run: 
    workflows: [Terraform Build Only]
    types: [completed]
    branches: 
      - "main"
      - "Automation" # TODO: undo after testing is complete

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env: 
      TF_VAR_AWS_ROOT_USER: ${{ secrets.AWS_ROOT_USER }}
      TF_VAR_AWS_IAM_USER: ${{ secrets.AWS_IAM_USER}}
      TF_VAR_AWS_DEPLOYMENT_ROLE: ${{ secrets.AWS_DEPLOYMENT_ROLE}}

    defaults:
      run:
        shell: bash
        working-directory: ./deployment/aws/terraform

    steps:
      - name: Checkout Github repository
        uses: actions/checkout@v4 
      
      - name: DEBUG - print default working dir and file contents
        run: pwd && ls
      
      - name: DEBUG - print workflow dir and file contents
        working-directory: ./.github/workflows/
        run: pwd && ls

      - name: DEBUG - print actions dir and file contents
        working-directory: ./.github/actions/setup-action/
        run: pwd && ls

      - name: Initialize runner
        uses: ./.github/actions/setup-action

      - name: Download Plan File
        uses: actions/download-artifact@v4
        with: 
          name: ${{ github.sha }}

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Deploy
        run: terraform apply $GITHUB_SHA



